GO
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaUno', N'Descripcion1', N'TipoUno', 1, 1, 2)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaDos', N'Descripcion2', N'TipoUno', 1, 0, 3)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaTres', N'Descripcion3', N'TipoDos', 1, 0, 5)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaCuatro', N'Descripcion4', N'TipoTres', 1, 1, 8)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaCinco', N'Descripcion5', N'TipoTres', 1, 1, 13)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaSeis', N'Descripcion6', N'TipoCinco', 0, 1, 21)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaSiete', N'Descripcion7', N'TipoSeis', 0, 0, 2)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaOcho', N'Descripcion8', N'TipoSiete', 0, 0, 3)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaNueve', N'Descripcion9', N'TipoSiete', 0, 1, 5)
INSERT [dbo].[Cabanias] ([Nombre], [Descripcion], [TipoNombre], [PoseeJacuzzi], [Habilitada], [MaxCupos])
	VALUES (N'CabaniaDiez', N'Descripcion10', N'TipoSiete', 0, 1, 7)
